### ISSUE TITLE
StackOverflow on recursive relationships in PowerPoint

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ARLM-Keller/officeotron#5]
```
What steps will reproduce the problem?
1. Try validating the attached document.
2. A StackOverflowError is thrown when processing the relationships

What is the expected output? What do you see instead?
 - Validation should pass successfully.

What version of the product are you using? On what operating system?
 - office-o-tron 0.5.4 on Windows 7 

Please provide any additional information below.

Relationships in PowerPoint might be recursive. In the attached sample
document e.g. slideLayout1.xml.rels contains a relation with the target
slideMaster1.xml, and slideMaster1.xml contains a relation with the target
slideLayout1.xml. 

Stack trace:

[07 Mai 2010 10:27:27,663] org.probatron.officeotron.Program INFO - Setting
temp dir to:
E:\Projects\OdfConverter\test\v4.0\officeotron-0.5.4\officeotron-tmp
[07 Mai 2010 10:27:27,663] org.probatron.officeotron.Program INFO - Init Store
[07 Mai 2010 10:27:27,664] org.probatron.officeotron.Program INFO - Create
OOXMLValidationSession
[07 Mai 2010 10:27:27,669] org.probatron.officeotron.Program INFO - Start
Prepare
[07 Mai 2010 10:27:27,707] org.probatron.officeotron.sessionstorage.Store
INFO - Executing command:
unzip.exe -qq
"E:\Projects\OdfConverter\test\v4.0\officeotron-0.5.4\officeotron-tmp\01a22e6c-3
33d-47bf-a5fa-f702e3e304d8\01a22e6c-333d-47bf-a5fa-f702e3e304d8"
-d
"E:\Projects\OdfConverter\test\v4.0\officeotron-0.5.4\officeotron-tmp\01a22e6c-3
33d-47bf-a5fa-f702e3e304d8"
[07 Mai 2010 10:27:28,237] org.probatron.officeotron.sessionstorage.Store
INFO - Finished executing command:
unzip.exe -qq
"E:\Projects\OdfConverter\test\v4.0\officeotron-0.5.4\officeotron-tmp\01a22e6c-3
33d-47bf-a5fa-f702e3e304d8\01a22e6c-333d-47bf-a5fa-f702e3e304d8"
-d
"E:\Projects\OdfConverter\test\v4.0\officeotron-0.5.4\officeotron-tmp\01a22e6c-3
33d-47bf-a5fa-f702e3e304d8".
return code=0
[07 Mai 2010 10:27:28,251] org.probatron.officeotron.zip.ZipArchive INFO -
Central directory NOT found
[07 Mai 2010 10:27:28,261] org.probatron.officeotron.Program INFO - Start
Validation
[07 Mai 2010 10:27:28,359] org.probatron.officeotron.OPCPackage INFO -
E:\Projects\OdfConverter\test\v4.0\officeotron-0.5.4\officeotron-tmp\01a22e6c-33
3d-47bf-a5fa-f702e3e304d8\docProps\_rels\core.xml.rels
(The system cannot find the path specified)
[07 Mai 2010 10:27:28,360] org.probatron.officeotron.OPCPackage INFO -
E:\Projects\OdfConverter\test\v4.0\officeotron-0.5.4\officeotron-tmp\01a22e6c-33
3d-47bf-a5fa-f702e3e304d8\docProps\_rels\thumbnail.jpeg.rels
(The system cannot find the path specified)
[07 Mai 2010 10:27:28,364] org.probatron.officeotron.OPCPackage INFO -
E:\Projects\OdfConverter\test\v4.0\officeotron-0.5.4\officeotron-tmp\01a22e6c-33
3d-47bf-a5fa-f702e3e304d8\ppt\_rels\presProps.xml.rels
(The system cannot find the file specified)
Exception in thread "main" java.lang.StackOverflowError
    at java.lang.String.startsWith(Unknown Source)
    at sun.misc.MetaIndex.mayContain(Unknown Source)
    at sun.misc.URLClassPath$JarLoader.getResource(Unknown Source)
    at sun.misc.URLClassPath$JarLoader.findResource(Unknown Source)
    at sun.misc.URLClassPath.findResource(Unknown Source)
    at java.net.URLClassLoader$2.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findResource(Unknown Source)
    at java.lang.ClassLoader.getResource(Unknown Source)
    at java.lang.ClassLoader.getResource(Unknown Source)
    at java.lang.ClassLoader.getResourceAsStream(Unknown Source)
    at org.apache.xerces.parsers.SecuritySupport$6.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.apache.xerces.parsers.SecuritySupport.getResourceAsStream(Unknown
Source)
    at org.apache.xerces.parsers.ObjectFactory.findJarServiceProvider(Unknown
Source)
    at org.apache.xerces.parsers.ObjectFactory.createObject(Unknown Source)
    at org.apache.xerces.parsers.ObjectFactory.createObject(Unknown Source)
    at org.apache.xerces.parsers.SAXParser.<init>(Unknown Source)
    at org.apache.xerces.parsers.SAXParser.<init>(Unknown Source)
    at sun.reflect.GeneratedConstructorAccessor1.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at org.xml.sax.helpers.NewInstance.newInstance(Unknown Source)
    at org.xml.sax.helpers.XMLReaderFactory.loadClass(Unknown Source)
    at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(Unknown Source)
    at org.probatron.officeotron.OPCPackage.procRels(Unknown Source)
    at org.probatron.officeotron.OPCPackage.procRels(Unknown Source)
    at org.probatron.officeotron.OPCPackage.procRels(Unknown Source)
    at org.probatron.officeotron.OPCPackage.procRels(Unknown Source)
    at org.probatron.officeotron.OPCPackage.procRels(Unknown Source)
    at org.probatron.officeotron.OPCPackage.procRels(Unknown Source)
    at org.probatron.officeotron.OPCPackage.procRels(Unknown Source)
    at org.probatron.officeotron.OPCPackage.procRels(Unknown Source)
    at org.probatron.officeotron.OPCPackage.procRels(Unknown Source)
    at org.probatron.officeotron.OPCPackage.procRels(Unknown Source)
    at org.probatron.officeotron.OPCPackage.procRels(Unknown Source)
[... truncated...]


```

Original issue reported on code.google.com by `Dirk.Vol...@gmail.com` on 7 May 2010 at 8:44

Attachments:
- [SimpleFile.pptx](https://storage.googleapis.com/google-code-attachments/officeotron/issue-5/comment-0/SimpleFile.pptx)

**Comment by GoogleCodeExporter** [comment]
```
Please note that this is a regression. Validation was working fine in 0.3.2
```

Original comment by `Dirk.Vol...@gmail.com` on 7 May 2010 at 8:52

**Comment by GoogleCodeExporter** [comment]
```
I re-enabled the check whether a relationship was already processed (this was 
in 0.3.2):

21a22
> import java.util.ArrayList;
34c35
<     // private ArrayList< String > foldersProbed = new ArrayList< String >();
---
>      private ArrayList< String > foldersProbed = new ArrayList< String >();
106,109c107,114
< 
<                 String potentialRelsUrl = f + "_rels/" + t.getFilename() + 
".rels";
<                 logger.debug( "*** Probing new possible target folder: " +
potentialRelsUrl );
<                 procRels( potentialRelsUrl ); // recurse
---
>                 if( !this.foldersProbed.contains( f ) )
>                 {
>                     this.foldersProbed.add( f );
>                 
>                   String potentialRelsUrl = f + "_rels/" + t.getFilename() + 
".rels";
>                   logger.debug( "*** Probing new possible target folder: " +
potentialRelsUrl );
>                   procRels( potentialRelsUrl ); // recurse
>                 }



```

Original comment by `Dirk.Vol...@gmail.com` on 7 May 2010 at 9:26

Attachments:
- [office-o-tron-soe.patch](https://storage.googleapis.com/google-code-attachments/officeotron/issue-5/comment-2/office-o-tron-soe.patch)

**Comment by GoogleCodeExporter** [comment]
```
Just noticed, that this problem has already been resolved in r56.
```

Original comment by `Dirk.Vol...@gmail.com` on 7 May 2010 at 9:33
